LAYERS = easyface.excellon 
LAYERS += easyface.dim
LAYERS += easyface.slt
LAYERS += easyface.mst
LAYERS += easyface.top
LAYERS += easyface.bot
LAYERS += easyface.msb
LAYERS += easyface.slb


all:
	gerbv ${LAYERS}

mkzip:
	zip easyface.zip ${LAYERS}

